#!/bin/bash
# FagiErrands API Health Check
# Runs endpoint tests and emails results to Gmail
# Designed for cPanel cron job

BASE_URL="https://api.errandserver.fagierrands.com/"  # <-- UPDATE THIS to your actual domain
REPORT_EMAIL="fagierrands0@gmail.com"                          # <-- UPDATE THIS to your Gmail
APP_DIR="/home3/distinc3/fagierrandsbackendapi"
PYTHON="$APP_DIR/venv/bin/python"
LOG_FILE="$APP_DIR/logs/health_check.log"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')
PASS=0
FAIL=0
REPORT=""

check() {
    local label="$1"
    local method="$2"
    local url="$3"
    local data="$4"
    local expected_status="$5"

    if [ -n "$data" ]; then
        response=$(curl -s -o /dev/null -w "%{http_code}" -X "$method" \
            -H "Content-Type: application/json" \
            -d "$data" \
            --max-time 15 \
            "$BASE_URL$url")
    else
        response=$(curl -s -o /dev/null -w "%{http_code}" -X "$method" \
            --max-time 15 \
            "$BASE_URL$url")
    fi

    if [ "$response" = "$expected_status" ] || [ "$response" = "200" ] || [ "$response" = "201" ] || [ "$response" = "400" ] || [ "$response" = "401" ] || [ "$response" = "405" ]; then
        status="✅ PASS"
        PASS=$((PASS + 1))
    else
        status="❌ FAIL (HTTP $response)"
        FAIL=$((FAIL + 1))
    fi

    REPORT="$REPORT\n  $status  [$method] $url  — $label"
}

# ── Server Health ──────────────────────────────────────────────
check "Homepage"                    GET  "/"                                    ""  200
check "Swagger Docs"                GET  "/swagger/"                            ""  200

# ── Auth Endpoints ─────────────────────────────────────────────
check "Register (validation check)" POST "/api/accounts/register/"             '{"email":""}' 400
check "Login (validation check)"    POST "/api/accounts/login/"                '{"email":""}' 400
check "Token endpoint"              POST "/api/accounts/token/"                 '{"username":"","password":""}' 400
check "Token refresh"               POST "/api/accounts/token/refresh/"         '{"refresh":"invalid"}' 401
check "Password reset request"      POST "/api/accounts/v1/password-reset/request/" '{"email":"test@test.com"}' 400
check "Resend OTP"                  POST "/api/accounts/resend-otp/"            '{"phone":""}' 400

# ── Errand / Order Endpoints ───────────────────────────────────
check "Orders list (auth required)" GET  "/api/orders/"                        ""  401
check "Create draft (auth required)" POST "/api/orders/errands/draft/"         ""  401
check "Calculate pricing"           POST "/api/orders/calculate-pricing/"      '{"distance":5}' 401
check "Config endpoint"             GET  "/api/orders/config/"                 ""  200
check "My orders (auth required)"   GET  "/api/orders/my-orders/"              ""  401

# ── Payment Endpoints ──────────────────────────────────────────
check "Initiate payment (auth req)" POST "/api/orders/payments/initiate/"      ""  401
check "NCBA QR generate"            POST "/api/orders/payments/ncba/qr-generate/" "" 401

# ── Location Endpoints ─────────────────────────────────────────
check "Locations API"               GET  "/api/locations/"                     ""  401

# ── Notification Endpoints ─────────────────────────────────────
check "Notifications (auth req)"    GET  "/api/notifications/"                 ""  401

# ── Build Report ───────────────────────────────────────────────
TOTAL=$((PASS + FAIL))
if [ "$FAIL" -eq 0 ]; then
    SUMMARY="🟢 ALL SYSTEMS OPERATIONAL — $PASS/$TOTAL passed"
else
    SUMMARY="🔴 ISSUES DETECTED — $PASS passed, $FAIL failed out of $TOTAL"
fi

BODY="FagiErrands API Health Check Report
======================================
Time   : $TIMESTAMP
Server : $BASE_URL
Result : $SUMMARY

Endpoint Results:
$(echo -e "$REPORT")

======================================
Auto-generated by cPanel cron job
"

# Log to file
echo "[$TIMESTAMP] $SUMMARY" >> "$LOG_FILE"

# Send email via sendmail (available on cPanel)
{
    echo "To: $REPORT_EMAIL"
    echo "From: noreply@fagierrands.com"
    echo "Subject: [FagiErrands] Health Check — $SUMMARY"
    echo "Content-Type: text/plain"
    echo ""
    echo "$BODY"
} | sendmail -t

echo "$BODY"
