# Generated by Django 4.2.30 on 2026-06-04 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: 254796605409', regex='^254\\d{9}$')]),
        ),
    ]
