# Generated by Django 4.2.30 on 2026-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Client'), ('assistant', 'Rider'), ('handler', 'Handler'), ('admin', 'Admin'), ('vendor', 'Vendor')], default='user', max_length=20),
        ),
    ]
