# Generated by Django 6.0.6 on 2026-07-18 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_account_manager_assistantverification_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantverification',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_assistants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Rider'), ('handler', 'Handler'), ('admin', 'Admin'), ('vendor', 'Vendor')], default='user', max_length=20),
        ),
    ]
