# Generated by Django 4.2.30 on 2026-05-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_plate_number'),
        ('accounts', '0100_create_token_blacklist_tables'),
    ]

    operations = [
    ]
