# Generated by Django 4.2.30 on 2026-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_sosalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Queued', 'Queued'), ('InTransit', 'In Transit'), ('PaymentPending', 'Payment Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
