# Generated by Django 4.2.30 on 2026-05-27 12:29

from django.db import migrations, models


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields only if they exist"""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_bankingorder' AND column_name='recipient_account'
                ) THEN
                    ALTER TABLE orders_bankingorder DROP COLUMN recipient_account;
                END IF;
                
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_bankingorder' AND column_name='recipient_name'
                ) THEN
                    ALTER TABLE orders_bankingorder DROP COLUMN recipient_name;
                END IF;
            END $$;
        """)


def add_index_if_not_exists(apps, schema_editor):
    """Add index to created_at only if it doesn't exist"""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE tablename = 'orders_order' 
                    AND indexname = 'orders_order_created_at_20b8d253'
                ) THEN
                    CREATE INDEX orders_order_created_at_20b8d253 ON orders_order (created_at);
                END IF;
            END $$;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_reportissue'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bankingorder',
            name='transaction_details',
            field=models.TextField(help_text='Cheque details: number, payee name, account to deposit into'),
        ),
        migrations.RunPython(add_index_if_not_exists, migrations.RunPython.noop),
    ]
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderprepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ncba', 'NCBA Till'), ('card', 'Card'), ('mpesa', 'M-Pesa (Legacy)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ncba', 'NCBA Till'), ('card', 'Card'), ('mpesa', 'M-Pesa (Legacy)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status', '-created_at'], name='idx_cli_stat_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assistant', 'status', '-created_at'], name='idx_ast_stat_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'assigned', 'in_transit', 'payment_pending'])), fields=['client', '-created_at'], name='idx_cli_act_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'assigned', 'in_transit', 'payment_pending'])), fields=['assistant', '-created_at'], name='idx_ast_act_cra'),
        ),
    ]
